version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/sample"
    schedule:
      interval: "weekly"
    groups:
      androidx:
        patterns:
          - "androidx.*"
          - "com.google.android.material:*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlinx:*"
      agp:
        patterns:
          - "com.android.tools.build:*"
